### ISSUE TITLE
Gemfile bundle error

### ISSUE THREAD

**Issue by bsemexan** [learn-co-curriculum/dynamic-orm-lab#15]
Dynamic ORM lab  - the initialize method doesn't work with 

BUNDLED WITH
   1.16.1

in Gemfile.lock
it work with 1.16.0 or below

**Comment by curiositypaths** [comment]
Hi there,

Would you mind providing a bit more detail about the issue? Things that are especially useful:
- An expanded explanation of what's going on.
- Steps to reproduce the issue.
- Details about your environment.
  + What's your operating system? Which version? What ruby version?
  + Are you using the Learn IDE or a local development environment?
- A [stack trace](https://en.wikipedia.org/wiki/Stack_trace) of any errors.

Thanks! 💙

**Comment by bsemexan** [comment]
ruby -v  :ruby 2.4.0p0
macOS  :10.13.3
reproduced both on learn and vscode
run bundle install
then you get 13 out of 15 tests failing.
this test is the issue: Student initialize creates a new student with attributes
with this error
```
NoMethodError:
       undefined method `id=' for #<Student:0x007fb8be90f1b8>
     # ./lib/student.rb:25:in `block in initialize'
     # ./lib/student.rb:24:in `each'
     # ./lib/student.rb:24:in `initialize'
     # ./spec/student_spec.rb:27:in `new'
     # ./spec/student_spec.rb:27:in `block (2 levels) in <top (required)>'
     # ./spec/student_spec.rb:53:in `block (3 levels) in <top (required)>'
```

**Comment by bsemexan** [comment]
so when replicating this, it seems I kind of didn't fully understand the instructions.
seems the student.rb file need to have the attr_accessor implemented for the initialize method to work?

**Comment by curiositypaths** [comment]
Correct, an `attr_accessor` should be dynamically defined for each column in the corresponding model table. We also recommend running ruby version `2.3.6`. The `2.4.x` release might cause issues with future lessons.
